### ISSUE TITLE
Load poster from api

### ISSUE THREAD

**Issue by claudiazanetel** [claudiazanetel/skisprint#7]
- [x] api to retrieve posters
- [x] bug in frontend
- [x] sort posters by year (desc)

**Comment by danieleorler** [comment]
@claudiazanetel 

to retrieve all posters:
`api.php?endpoint=posters`

to retrieve a single poster:
`api.php?endpoint=posters&year=2005`

posters have the following json representation:
```json
{
   "year": 2005,
   "path": "/files/poster/poster_2015.jpg"
}
```
